### ISSUE TITLE
Add exception support?

### ISSUE THREAD

**Issue by sethrj** [sethrj/swig#10]
Add a module-level error code (and string message?) for printing

**Comment by wawiesel** [comment]
The best thing I can think of for exception support would be a way to tell swig to wrap a method/function call with special support for a specific type of exception. This would put a try/catch block in the body for that exception type only.

```c
void something_that_throws(float a , float b, float c, std::string& msg)
{
    try{
       ...
    } catch( const ExceptionType& e ){
        msg=e.what();
    }
}
```

The fortran would then be given that message as an optional return argument.

```fortran
subroutine something_that_throws(a,b,c,exception_msg)
real :: a,b,c
character(*),optional,intent(out) :: exception_msg
type(std_string) :: msg
call c_something_that_throws(a,b,c,msg)
if( present(exception_msg) )then
    exception_msg=msg
else
    write(0,*)msg.f_str()
    stop 1
endif
end subroutine

``` 

I don't think the module level error code and string message will work in general--e.g. free functions or multiple classes per module.

**Comment by sethrj** [comment]
The problem with this is that exception support is typically an optional feature, and I don't like the idea of changing every function signature based on whether exception support is enabled. (Plus, are all functions going to have exceptions, or only some? How is the user supposed to keep track of what needs the exception argument and what doesn't?) So what I was envisioning is something like the following in the C++ wrapper code:
```
std::string g_exception_msg;

bool error()
{
    return !g_exception_msg.empty();
}

void clear_error()
{
    g_exception_msg.clear();
}

void get_error_msg(char* STRING, int SIZE)
{
    /* copy error message to fortran string */
}

void wrap_foo()
{
    if (error())
    {
        cout << "A previously thrown exception ("
            << g_exception_msg << ") was not handled; terminating"
            << endl;
        std::terminate();
    }

    try
    {
        foo()
    }
    catch (const std::logic_error& e)
    {
        exception_msg = e.what();
    }
}
```

Since this causes the exception type to be lost (and can delay finding out about the exception), I'd make exception wrapping optional to aid in debugging.

**Comment by wawiesel** [comment]
Is ``g_exception_msg`` global? 

If not, the problem with this approach I think, and mine too, is that there will be unavoidable issues if there is more than one exception in the client code. In my case, there's no way the right message will make it back. In your case, you could end up in the ``if( error())`` section without ever having a chance to do something. So assuming, ``g_`` is global, I think you just need to pass through any calls once the first exception is thrown.
```c++
void wrap_foo()
{
    if (!error())
    {
        try
        {
            foo()
        }
        catch (const std::logic_error& e)
        {
            g_exception_msg = e.what();
        }
    } 
    else 
    {
        cout << "A previously thrown exception ("
            << g_exception_msg << ") has not been handled!"
            << endl;
    }
}
```
Maybe there could be an option to terminate, though? So two options: SWIG_FORTRAN_CATCH_EXCEPTIONS=YES|NO and SWIG_FORTRAN_ALLOW_UNCAUGHT

**Comment by sethrj** [comment]
Yeah, it's meant to be a global/static variable. By "more than one exception in the client code", do you mean multiple exceptions from multiple client calls without clearing the exception in between? I don't think that should be allowed -- the only reason not to terminate immediately is to let Fortran handle the error.

You definitely *don't* want to allow what would normally be fatal errors to be converted to warnings (which often get ignored by users right?). On a related note: https://github.com/ajalt/fuckitpy

**Comment by sethrj** [comment]
OK, this is now implemented. When exceptions are enabled by including `<std_except.i>` or `<exceptions.i>`, a Fortran module integer `ierr` (which can be configured) is defined in the code. SWIG will catch any errors and set that code as well as a string with the message; the string can be retrieved by a subroutine call. The error can be cleared by the fortran module by resetting `ierr` to zero; otherwise, the next time a function is called, the error will be rethrown as "Uncaught exception: msg".
