### ISSUE TITLE
Handle raw structs

### ISSUE THREAD

**Issue by youngmit** [sethrj/swig#11]
Right now we don't handle simple POD structs very well. The ret_by_value.i interface in the test suite is a good example. There are a couple of ways we could do this; we could provide accessor functions to the public members, or if a struct is simple enough, we could wrap it as an interoperable type and move it around by value. See: https://gcc.gnu.org/onlinedocs/gfortran/Derived-Types-and-struct.html#Derived-Types-and-struct

**Comment by sethrj** [comment]
We might be able to add a "feature" directive that allows switching from a proxy class to a C-bound fortran struct. We'd definitely want the user to have to manually specify this. I guess we could also then use fortran pointers for wrapping these in return-by-reference?

**Comment by sethrj** [comment]
Initial implementation completed by #57
