### ISSUE TITLE
Add support for multi-dimensional arrays

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#18]
Probably, using `C_F_Pointer`

**Comment by sethrj** [comment]
[Documentation](https://gcc.gnu.org/onlinedocs/gfortran/C_005fF_005fPOINTER.html)

**Comment by sethrj** [comment]
This should be possible now with #36 merged. You'll want to override the `fout` typemap for the class in question.

**Comment by aprokop** [comment]
Should not the support for multi-dimensional require extension of `std::pair` to something like `std::tuple`?

**Comment by sethrj** [comment]
I think you'd want to build a custom data structure (or multiple function calls using `fout`) tailored to the specific application. I don't envision creating a general `fortran_multid_view`, though I don't think it would be too hard to create `fortran_2d_view`, `fortran_3d_view`, etc.

**Comment by sethrj** [comment]
This should be straightforward with the existing typemap capability. Since there's no native C/C++ multidimensional array, it's going to have to be up to the library developer (possibly/presumably with my help) to add this capability.
