### ISSUE TITLE
SwigModules.cmake does not work with cmake-3.8+

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#25]
Startin with CMake 3.8.0, the TYPE property became read only, resulting in
```bash
CMake Error at cmake/SwigModules.cmake:200 (set_target_properties):
  TYPE property is read-only
```

CMake 3.7.2 works fine.

**Comment by aprokop** [comment]
[Here](https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=98f2143305b8b8c5ce08dfa38ee79750696865a6) is the corresponding commit making the change.

**Comment by aprokop** [comment]
@sethrj Do you have any thoughts on this? I've been bitten a bunch of times on this...

**Comment by sethrj** [comment]
Fixed with 727fb9fa4716d26905eed2236e961de87bfac059

**Comment by aprokop** [comment]
Right now, the Examples/fortran in SWIG only with work with CMake 3.8, but no 3.7.2 (the reverse problem).

**Comment by aprokop** [comment]
One thing I noticed is that it should probably be `"f90"` instead of `".f90"` for extensions.

**Comment by aprokop** [comment]
OK, something is weird: I had to remove the `.` for ForTrilinos as it could not find files like `fortrilinos..f90`. But inside SWIG, it seems that if I removed the dot, it fails to configure at all.

**Comment by sethrj** [comment]
Oh, I remember I had to add a dot extension. But I don't think I made that an exception for the older CMake. Maybe in the header where the version check is being done, make it `.f90` for the newer cmake but `f90` for the older.
