### ISSUE TITLE
Add a flag to ignore a function when $fclassname replacement not found

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#27]
I have the following declaration in `Tpetra_Map_decl.hpp`:
```c++
    Map (const global_size_t numGlobalElements,
         const Teuchos::ArrayView<const GlobalOrdinal>& indexList,
         const GlobalOrdinal indexBase,
         const Teuchos::RCP<const Teuchos::Comm<int> >& comm,
         const Teuchos::RCP<Node>& node = defaultArgNode<Node>());
```
SWIG knows about all types except for the Node. I don't need a constructor with a Node in the near future, and only want the default value for it. However, in `fortan.cxx` we have:
```c++
        // use $descriptor if SWIG does not know anything about this type.
        // Note that any typedefs are resolved.
        Swig_warning(WARN_FORTRAN_TYPEMAP_FTYPE_UNDEF,
                     input_file, line_number,
                     "No '$fclassname' replacement (wrapped type) "
                     "found for %s\n",
                     SwigType_str(classnametype, 0));

        replacementname = NewStringf("SWIGTYPE%s",
                                     SwigType_manglestr(classnametype));

        Replaceall(tm, classnamespecialvariable, replacementname);
        Delete(replacementname);
```
which unconditionally generates the replacement name. Instead, I'd like for it to skip this function. Is this something achievable?

@sethrj

**Comment by sethrj** [comment]
I think you can tell SWIG to `%ignore` the overloaded version of the function that has the extra argument.

**Comment by aprokop** [comment]
@sethrj Maybe, that I would really like for it to do is by default ignore anything isn't available. This way, you can run it on file and produce a minimal interface that is recognizable. Otherwise, as you say, you would need to go through functions one by one and add `%ignore`. Could take a while if there are many functions.
