### ISSUE TITLE
Add support for "*&" in typemaps

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#4]
`Epetra_BlockMap` has for example the following function:

```c++
class Epetra_BlockMap {
...
  int MyGlobalElementsPtr(int *& MyGlobalElementList) const;
...
};
```
Currently, this results in Fortran types being `SWIGTYPE_p_p_int`.

**Comment by sethrj** [comment]
This is effectively getting a pointer to a pointer; unless we want to wrap opaque C pointers in fortran (`int*`) there's no way to incorporate this into the SWIG language. I think it would be better to ignore this function and add a custom wrapper that returns the values or something.
