### ISSUE TITLE
Fix use of c_loc with variable-length strings

### ISSUE THREAD

**Issue by sethrj** [sethrj/swig#40]
According to [the standard](https://software.intel.com/en-us/node/678435), the [`C_LOC`](https://software.intel.com/en-us/node/679093#C22E0C49-56D0-4642-98D4-82FE7A65B004) function doesn't work with assumed-length character arrays. Instead see about directly casting to `char*`.

"Scalar variables are interoperable only if [...] and if character length is not assumed nor defined by a non-constant expression." and for `C_LOC`: "A scalar that has no length type parameters and [...]"

Currently, this function I have that takes two string arguments produces:
```
00000120: 2020 2020 2020 2032 310a 2053 7472 696e         21. Strin
00000130: 673a 0000 0000 0000 00a0 0000 0000 0000  g:..............
00000140: 00a0 0400 6569 6969 696e 6767 6767 203c  ....eiiiingggg <
00000150: 2d20 7761 7320 616c 736f 2061 2073 7472  - was also a str
00000160: 696e 670a                                ing.
```
so somehow the data has been replaced with zeroes.

Also in the future (F2015 if that ever gets implemented) : Fortran standard will require a `ISO_Fortran_binding.h` file that should allow advanced interaction with fortran data from C/C++ via SWIG.

**Comment by sethrj** [comment]
Actually it looked like this issue was because the return value was going out of scope, so I was accessing invalid memory. Still need to look into how to return a `std::string` by value and convert the result to a fortran allocatable string.

**Comment by bscollin** [comment]
Interesting note, when I run with gcc 5.4.0 and use the fortran flag `-std=f2003`, it also compiles file.  I greatly appreciate the patch though.

**Comment by sethrj** [comment]
Yeah, I've been using the standards-compliant flags as well. But these changes might improve compiler compatibility elsewhere too, which is highly desirable...
