### ISSUE TITLE
Allow fortran file extention to be F90 instead of f90

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#41]
Doxygen does not work with Fortran files that end with `.f90`. But it does work with `.F90`.

**Comment by sethrj** [comment]
Sounds like a Doxygen issue, not a SWIG issue?

**Comment by aprokop** [comment]
It is, but the workaround is to replace our f90 file extensions with F90. Not a big deal. I found the option you provided and I'll just use
```
set(SWIG_FORTRAN_EXTRA_FILE_EXTENSIONS "F90")# 
```
in ForTrilinos if you have no objections.

**Comment by sethrj** [comment]
Sure, sounds good.
