### ISSUE TITLE
Make non-scalar return values pass-by-reference dummy variables?

### ISSUE THREAD

**Issue by sethrj** [sethrj/swig#44]
Now that I have so much experience with SWIG and its innards, I think we might be able to solve some of the lingering memory issues—namely, the ambiguity of creation/destruction when returning from a function; the inability to tell what's a reference and what's a value. This is why RCP counting doesn't quite work right.

So I propose that in the proxy code, all non-intrinsic types are transformed from returning as a `function` call to being passed in as an `intent(inout)` parameter. (`inout` allows us to call release() on the passed value before assigning it). (I still think we can return views.)

@aprokop If I do this change it will require refactoring of the fortrilinos interface. But I think this methodology would be the most Fortran-friendly.

- [ ] Add fragment defining C struct `SwigfData` for SWIG data: {void* pointer, bool ownership} (note that later we may add const char* datatype for multiple inheritance etc)
- [ ] Add fortran `BIND(C)` fragment for `SwigfData`
- [ ] Add `fdata` type  that defaults to the above for classes
- [ ] Add feature+typemap `subroutine` (just like `fout` has both) to decide whether proxy function should act like a subroutine
- [x] Break up interface writing/proxy function writing/C interface writing?
- [ ] `Copy(params)` and `NewParm` and `Append`
- [ ] Adjust typemaps for SWIG classes so that return-by-value accepts ownership and -by-reference doesn't
- [ ] Add assignment operator for `operator=`: actually do object copy instead of trying to fiddle with pointers (let the fortran user make a pointer if desired)

**Comment by aprokop** [comment]
@sethrj It would make it easier for me to understand if you could provide an example of before and after this change.

**Comment by sethrj** [comment]
Good point @aprokop . Should document it for my own purposes too.

Before:
```fortran
function make_class(val) &
        result(swigf_result)
    use, intrinsic :: ISO_C_BINDING
    type(SimpleClass) :: swigf_result
    integer(C_INT), intent(in) :: val
    type(C_PTR) :: fresult 
    integer(C_INT) :: farg1 

    farg1 = val
    fresult = swigc_make_class(farg1)
    swigf_result%swigptr = fresult
end function
```
would be called like
```fortran
type(SimpleClass) :: made
made = make_class(2)
```

---

After:
```fortran
type, protected, bind(C) :: SwigfData
  type(C_PTR), public     :: data
  logical(C_BOOL), public :: owns
end type

subroutine make_class(val, swigf_result) &
        use, intrinsic :: ISO_C_BINDING
    integer(C_INT), intent(in) :: val
    type(SimpleClass), intent(inout) :: swigf_result
    type(SwigfData) :: fresult 
    integer(C_INT) :: farg1 

    farg1 = val
    fresult = swigc_make_class(farg1)
    call swigf_result%release()
    swigf_result%swigdata = fresult
    ! note that swigf_result%swigdata%owns will be set to .true.
    ! by the C wrapper
end function
```

called like:
```fortran
type(SimpleClass) :: made
call make_class(2, made)
```

---

Before, 
```fortran
type(SimpleClass) :: made
made = make_class(2)
made = make_class(3)
call made%release()
```
would leak memory between the two `make_class` calls, but now
```fortran
type(SimpleClass) :: made
call make_class(2, made)
call make_class(3, made)
call made%release()
```
will not leak (because now we can call `release` on the object passed into the
subroutine)

**Comment by aprokop** [comment]
Could the same effect be achieved through overloading `interface assignment(=)`?

**Comment by sethrj** [comment]
No, because the destination is `intent(out)` and can't be modified.

**Comment by sethrj** [comment]
I'm not going to do this.

**Comment by sethrj** [comment]
OK maybe I will, since it seems to be the only possible way of preventing temporary classes from screwing up assignment semantics.

**Comment by sethrj** [comment]
Basically, Fortran doesn't have copy elision: when you call `f = do_function(arg)`, the `assignment(=)` generic seems to be called *no matter what*, and the temporary (the return value of `do_function` and the second argument of the assignment) is lost.

**Comment by sethrj** [comment]
OK, never mind, I think I can fake a "move" operation by using a flag that gets set when returning from  a function and cleared inside the assignment operator.

**Comment by sethrj** [comment]
Closing; subsumed by #58
