### ISSUE TITLE
Make generated file extension configurable

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#48]
There are situations when we may want to use `F90` instead of `f90`. However, right now this is hardcoded:
```C
void FORTRAN::write_module()
{
    // Open file
    String* path = NewStringf(
            "%s%s.f90", SWIG_output_directory(), Char(d_module));
    File* out = NewFile(path, "w", SWIG_output_files());
```

**Comment by sethrj** [comment]
Implemented in `4407006a8`: add the SWIG command line option `-fext F90` to the cmake SWIG flags.
