### ISSUE TITLE
Fix `MAKE_SWIG` Cmake macro

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#5]
It seems that updating `.i` file does not necessairly lead to regenerating `.f90` file.

Current workaround is to first run `make clean`

**Comment by sethrj** [comment]
Can you verify that this is the case? The dependency logic has worked for a long time on my other projects, and it seems to work with this one for me at least.

**Comment by aprokop** [comment]
I'll try to find some time today to take another look at it.
