### ISSUE TITLE
Include hash of the SWIG commit in the header

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#50]
Sometimes, the most recent SWIG fails, and there is need to revert back. However, if this is noticed too late, it is no longer clear which commit to go back to. I propose to include the hash of the SWIG commit that was used into the wrapper files.

**Comment by sethrj** [comment]
I don't think this is feasible -- the SWIG build system doesn't have the introspection to know the git hash; and since it's using autoconf rather than something like CMake, it would be extremely difficult to add.

**Comment by aprokop** [comment]
What about a workaround for now: add git hooks (post-checkout, etc) that would hardcode the git version into a string in SWIG/fortran? This does not have to be a long-term solution, just something until we merge SWIG upstream.

**Comment by sethrj** [comment]
If you can create the git hook, I'll integrate it into the Fortran headers.

**Comment by sethrj** [comment]
See https://github.com/swig/swig/pull/1101 ; there is apparently enough contention about this (and difficulties with its implementation) that I'm going to stay out of it.

**Comment by aprokop** [comment]
Reading through that thread, it seems that people agree it is a good idea, but not sure about the way to approach that.
