### ISSUE TITLE
Default template argument workaround

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#53]
Only this specific way works:
- `%teuchos_rcp` (or `%shared_ptr`) specify the default argument
- `%template` to not use it

Here is a small example (all 4 functions' signatures are properly recognized):
```
%module A

%include <std_shared_ptr.i>

typedef int NO;

%shared_ptr(A<NO, NO::classic>)

template<class T, const bool classic = T::classic>
class A {
public:
    int g(const A<T>& b);
    int f(const A<T,classic>& b);
    int gs(std::shared_ptr<A<T> > bsp);
    int fs(std::shared_ptr<A<T,classic> > bsp);
};

%template(At) A<NO>;
```

**Comment by sethrj** [comment]
I'm confused -- what's broken? What's a failing case and expected behavior in that case?

**Comment by aprokop** [comment]
If you try to do
```
%teuchos_rcp(A<NO, NO::classic>)
...
%template(At) A<NO, NO::classic>;
```
that does not work. If you try
```
%shared_ptr(A<NO>)
...
%template(At) A<NO>;
```
that also does not work.

**Comment by sethrj** [comment]
OK, I've reproduced the problem, and I suspect it has something to do with SWIG's ability to look up embedded template parameters:
```swig
%module issue53

%include <std_shared_ptr.i>

%inline %{
struct NO {
    enum { classic = 1 };
};
%}

%inline %{
template<class T, int classic = T::classic>
class A {
public:
    int g(const A<T>& b);
    int f(const A<T,classic>& b);
    int gs(std::shared_ptr<A<T> > bsp);
    int fs(std::shared_ptr<A<T,classic> > bsp);
};
%}

%shared_ptr(A<NO, NO::classic>)
%template(At) A<NO>;
```

**Comment by sethrj** [comment]
In the above example, if you export the symbol tables by running
```sh
swig -debug-symtabs -fortran -c++ issue53.i
```
it prints the following summary:
```
SYMBOL TABLES SUMMARY start  =======================================
+++  - 0x100924a00 ----------------------------------------
|              - 0x100924940
| std::shared_ptr<(A<(NO,NO::classic)>)> - 0x100c8aec0
| std::shared_ptr<(q(const).A<(NO,NO::classic)>)> - 0x100c94d20
| std::initializer_list - 0x100944fe0
| A            - 0x100c7f9c0
| std          - 0x100944bc0
| A<(NO,NO::classic)> - 0x100c95140
| std::shared_ptr - 0x100c7eb20
| NO           - 0x100c7f1a0
| A<(NO)>      - 0x100c95140
|
SYMBOL TABLES SUMMARY finish =======================================
```
Note that `A<(NO)>` and `A<(NO,NO::classic)>` point to the same object, and note that `%shared_ptr(A<NO, NO::classic>)` is present but `%shared_ptr(A<NO>)` isn't.

------

When you change the interface to
```swig
%shared_ptr(A<NO>)
%template(At) A<NO>;
```
it does expand the embedded classes and the `$fclassname` warning is no longer printed. The new symbol table correctly shows all the class and expansions:
```
SYMBOL TABLES SUMMARY start  =======================================
+++  - 0x107fe1a00 ----------------------------------------
|              - 0x107fe1940
| std::shared_ptr<(A<(NO)>)> - 0x108346d40
| std::shared_ptr<(q(const).A<(NO)>)> - 0x10834fe00
| std::initializer_list - 0x108001fe0
| A            - 0x10833c9c0
| std          - 0x108001bc0
| A<(NO,NO::classic)> - 0x108350c80
| std::shared_ptr - 0x10833bb20
| NO           - 0x10833c1a0
| A<(NO)>      - 0x108350c80
|
SYMBOL TABLES SUMMARY finish =======================================
```

In the example you posted, `typedef int NO;` isn't valid when you do `NO::classic`; I bet that was  the problem you originally had? Similarly, the `fortpetra.i` didn't tell SWIG anything about NO, so NO::classic was an opaque type. Adding
```c++
namespace Kokkos { namespace Compat {
struct KokkosSerialWrapperNode {
  static const bool classic = false;
};
} }
```
to the interface file, and then also moving the `shared_ptr` *after* the class declaration, fixes it.

I've updated the Tpetra Multivector class accordingly on a branch.
