### ISSUE TITLE
Wrapped ostream support

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#6]

**Comment by youngmit** [comment]
What do you mean by "marry?" Somehow redirect what is sent through a print/write statement to an existing ostream on the C++ side? Are we making any assumptions about where the output from the ostream directed? My guess is doubtful in the general case; the fortran I/O capabilities are pretty restrictive to just files and standard in/out/error streams, without much flexibility. I don't know of any way to bind a fortran I/O unit to just any stream buffer.

**Comment by youngmit** [comment]
Also, sorry ive been so quiet. I got hit with the flu and haven't been able to keep up with things last several days...

**Comment by aprokop** [comment]
Lets say we have a function
```c++
std::ostream& f(std::ostream& os, double x) {
  os << x << std::endl;
}
```
Can we store some object corresponding to `std::ostream` in fortran and then somehow `print` into it in Fortran?

Or should we, by default, for any classes that have this function, simply do `std::cout` print of things that are in that `std::ostream` without passing them to Fortran?

**Comment by youngmit** [comment]
I see... not that I am aware of. There may be some deep secrets of the
WRITE statement and the corresponding unit that you are writing to that
would allow this, but a haven't been able to find anything useful. Fortran
uses "unit" numbers to direct I/O, which are either associated with a file
using OPEN, much like file handles in C, or with standard out/in/error
using magic numbers. The ISO_FORTRAN_ENV module provides
implementation-independent values for output_unit, input_unit and
error_unit.

My guess is ultimately that we will have to handle wrapping these kinds of
functions in a more fortran- or c++-centric way on a case-by-case basis.

On Wed, Jan 25, 2017 at 6:02 PM, Andrey Prokopenko <notifications@github.com

**Comment by wawiesel** [comment]
I think this type of function
```c++
std::ostream& f(std::ostream& os, other_type x) {
    os << x << std::endl;
}
```
should be mapped to a fortran
```fortran
subroutine f( os , x )
type(std_ostream) :: os
type(other_type) :: x
    call c_wrapper_f(os,x)
end subroutine
```
with the c wrapper:
```c
void c_wrapper_f(std::ostream& os, other_type x) {
    f(os,x);
}
```
The ``std_ostream`` type should be a fortran bound type of the ``std::ostream``. But because fortran cannot easily have operator behavior like with ``<<`` or ``>>`` I would recommend just providing all the fundamental types and string with something generic like ``std_ostream.append(x)``.
```fortran
type(std_ostream) :: os
type(other_type) :: x
    call os.append( 1.0 ) !eventually does os<<1.0;
    call os.append( 33 ) !eventually does os<<33;
    call os.append( "hello" ) !eventually does os<<"hello";
    call os.append( x ) !fails because z is not one of the fundamental types
``` 
And handling other more general classes requires a bound routine like ``f`` above.
```fortran
call f(os,x) !succeeds because f is a special bound writing function
``` 
I think being able to do a good binding of the ``ostream`` classes is extremely important because fortran's input and output are so limited, especially in parallel calculation scenarios.  It will be nowhere as beautiful as the C++ variant, but if it can have 20-50% of the functionality I would consider it a success.

**Comment by sethrj** [comment]
Good point @wawiesel . Do you think we should only wrap `ostringstream`, or also try to provide native bindings to cout/cerr/ofstream/... ?

For the builtin vs user-type ostream question: since fortran supports overloading through the generic statement, couldn't we just have something like
```
subroutine swrite(os, value)
```
overloaded to the different fundamental and user types in a module? It would almost be more idiomatic for Fortran since the built-in write functions take an I/O unit IIRC.

**Comment by wawiesel** [comment]
Yeah @sethrj, I think you're right about something like swrite. That's better than the ``os.append`` I was suggesting. I think ideally you build the ``swrite`` functions taking an ``std::ostream` binding and mimic the C++ for cout/cerr/ofstream/ostringstream.

So you could use the standard streams like this

```fortran
use std_iostream_m,only: std_cout, std_cerr
call swrite(std_cout, 1.0)
call swrite(std_cerr, "hello")
```

Or the ofstream like this

```fortran
use std_ofstream_m
type(std_ofstream) :: ofs
ofs.open("some_file.txt")
call swrite(ofs, "hello again") 
ofs.close()
```

Or the stringstream like this

```fortran
use std_sstream_m
type(std_stringstream) :: ss
character(len=:),allocatable :: return_string(:)
call swrite(ss,0.0)
return_string = ss.str() !contains 0.0 
```

**Comment by sethrj** [comment]
Yeah. I'm not sure how to bind `cout` and `cerr` as module-level fortran proxy classes to C++ global variables though.

**Comment by wawiesel** [comment]
I have a working prototype here: 
https://github.com/wawiesel/BOTG-TEMPLATE/blob/std_ostream_bindings/src/TMPL/f/Demo_M.f90

I don't think there's any way around having to initialize Fortran's cout one time somewhere.

Here's the relevant fortran modules. I am providing the ``std_cout`` variable globally, but require it to be initialized somewhere with a call to ``f_connect_std_cout``.

```fortran
module std_ostream_m
use ISO_C_BINDING

implicit none

type std_ostream
    type(C_PTR) :: instance_ptr = C_NULL_PTR
end type

type(std_ostream) std_cout

interface

    type(C_PTR) function f_std_ostream_cout() &
        BIND(C,name="c_std_ostream_cout")
        use ISO_C_BINDING
    end function

    subroutine f_TMPL_swrite_double(os,x) BIND(C,name="c_TMPL_swrite_double")
        use ISO_C_BINDING
        type(C_PTR),value :: os
        real(C_DOUBLE),value :: x
    end subroutine

    subroutine f_TMPL_swrite_string(os,x) BIND(C,name="c_TMPL_swrite_string")
        use ISO_C_BINDING
        type(C_PTR),value :: os
        character(1),value :: x
    end subroutine

end interface

interface swrite
    module procedure :: TMPL_swrite_double
    module procedure :: TMPL_swrite_string
end interface
public :: std_cout

contains

    subroutine f_connect_std_cout()
        std_cout % instance_ptr = f_std_ostream_cout()
    end subroutine

    subroutine TMPL_swrite_double(os,x)
        class(std_ostream),intent(inout) :: os
        real(C_DOUBLE),intent(in) :: x
        call f_TMPL_swrite_double(os%instance_ptr,x)
    end subroutine

    subroutine TMPL_swrite_string(os,x)
        class(std_ostream),intent(inout) :: os
        character(*),intent(in) :: x
        call f_TMPL_swrite_string(os%instance_ptr,x//C_NULL_CHAR)
    end subroutine

end module


module std_ofstream_m
use ISO_C_BINDING
use std_ostream_m

implicit none

type, extends(std_ostream) :: std_ofstream
contains
    procedure, pass(this) :: create=>std_ofstream_create
    procedure, pass(this) :: close=>std_ofstream_close
end type

interface

    type(C_PTR) function f_std_ofstream_create(file) &
        BIND(C,name="c_std_ofstream_create")
        use ISO_C_BINDING
        character(len=1),value :: file
    end function

    subroutine f_std_ofstream_close(ofs) &
        BIND(C,name="c_std_ofstream_close")
        use ISO_C_BINDING
        type(C_PTR), value :: ofs
    end subroutine

end interface

contains

    subroutine std_ofstream_create(this,file)
        class(std_ofstream) :: this
        character(*),intent(in) :: file
        this%instance_ptr = f_std_ofstream_create(file//C_NULL_CHAR)
    end subroutine

    subroutine std_ofstream_close(this)
        class(std_ofstream) :: this
        call f_std_ofstream_close(this%instance_ptr)
        this%instance_ptr = C_NULL_PTR
    end subroutine

end module


module std_sstream_m
use ISO_C_BINDING
use std_ostream_m

implicit none

type, extends(std_ostream) :: std_sstream
contains
    procedure, pass(this) :: create=>std_sstream_create
    procedure, pass(this) :: close=>std_sstream_close
    procedure, pass(this) :: str=>std_sstream_str
end type

interface

    type(C_PTR) function f_std_sstream_create() &
        BIND(C,name="c_std_sstream_create")
        use ISO_C_BINDING
    end function

    subroutine f_std_sstream_close(ss) &
        BIND(C,name="c_std_sstream_close")
        use ISO_C_BINDING
        type(C_PTR), value :: ss
    end subroutine
    subroutine f_std_sstream_length(ss,n) &
        BIND(C,name="c_std_sstream_length")
        use ISO_C_BINDING
        type(C_PTR), value :: ss
        integer(C_INT) :: n
    end subroutine
    subroutine f_std_sstream_str(ss,n,str) &
        BIND(C,name="c_std_sstream_str")
        use ISO_C_BINDING
        type(C_PTR), value :: ss
        integer(C_INT) :: n
        character(1) :: str
    end subroutine

end interface

contains

    subroutine std_sstream_create(this)
        class(std_sstream) :: this
        this%instance_ptr = f_std_sstream_create()
    end subroutine

    subroutine std_sstream_close(this)
        class(std_sstream) :: this
        call f_std_sstream_close(this%instance_ptr)
        this%instance_ptr = C_NULL_PTR
    end subroutine

    function std_sstream_str(this) result(str)
        class(std_sstream) :: this
        character(len=:),allocatable :: str
        integer(C_INT) :: n
        call f_std_sstream_length(this%instance_ptr,n)
        allocate( character(len=n) :: str )
        call f_std_sstream_str(this%instance_ptr,n,str)
    end function

end module
```

**Comment by sethrj** [comment]
I don't think it's feasible for us to write an integrated Fortran-friendly stream at this time.
