### ISSUE TITLE
Add "char*" typemaps

### ISSUE THREAD

**Issue by aprokop** [sethrj/swig#7]
In progress.

So far, for a reason I don't understand, given a function
```c++
  void SetLabel(const char* Label_in);
```
SWIG searches typemaps for `char const *` and not `const char *`. This seems to be different from other types.

**Comment by sethrj** [comment]
Those two types are equivalent as far as SWIG goes (it just rearranges it for its internal purposes), but I'll have to check on what `const char*` converts to

**Comment by aprokop** [comment]
Some progress was done in #13. Still need to do a lot more there.

**Comment by sethrj** [comment]
`const char*` and `char*` support is in and tested. Note again that since Fortran doesn't have null-terminated strings, it will generally always be necessary to pass in a "string length" argument alongside a char pointer.
