### ISSUE TITLE
Add Fortran examples and integrate into SWIG test framework

### ISSUE THREAD

**Issue by youngmit** [sethrj/swig#9]
We already have a fist full of example/test code, but none of it is integrated into the existing SWIG testing framework. Should consolidate and add to SWIG build system.

**Comment by youngmit** [comment]
See branch fort_build_system. This should follow most of the conventions of the existing SWIG build system, and enables the test suite for fortran. I am going to tighten some more bolts, then this should be good to merge in.

**Comment by sethrj** [comment]
Done a long time ago.
